name: go-pihole-build

on:
  push:

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: go test
        run: |
          go test -cover ./...

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: build
        run: |
          cd cmd
          go build

