name: go-pihole-security-check

on:
  push:

jobs:
  security-check:
    name: security-check
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout project
        uses: actions/checkout@v2
      -
        name: Salus Scan
        run: |
          docker run --rm -t \
            -v $(pwd):/home/repo coinbase/salus \
            --config "file://salus-config.yml"
